### ISSUE TITLE
Snakemake Plugin Catalog only displays executor plugins

### ISSUE THREAD

**Issue by cmeesters** [snakemake/snakemake-plugin-catalog#7]
see title and screenshot
![Screenshot from 2024-07-05 14-37-29](https://github.com/snakemake/snakemake/assets/9866827/75906e5a-fd28-4937-b38c-cbec595f4259)

Any ideas?

**Comment by dlaehnemann** [comment]
I transferred this over here, where I think it belongs. And I am not familiar with the code for this one, yet. So no real idea here. But since basically nothing has changed in this repository for the last 3 months, I am assuming something went wrong with the daily depley cron job one of these past days:
https://github.com/snakemake/snakemake-plugin-catalog/actions

**Comment by dlaehnemann** [comment]
There seem to be [deprecation notices for some of the GitHub Actions versions](https://github.com/snakemake/snakemake-plugin-catalog/actions/runs/9803263953) in use, so maybe we should simply try updating all GitHub Actions to the newest versions. As the CI logs will go away, here's the current notice:

> **deploy**
The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v3, actions/configure-pages@v3, actions/upload-artifact@v3, actions/deploy-pages@v1. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/

> **Deprecation notice: v1, v2, and v3 of the artifact actions**
The following artifacts were uploaded using a version of actions/upload-artifact that is scheduled for deprecation: "github-pages".
Please update your workflow to use v4 of the artifact actions.
Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

**Comment by dlaehnemann** [comment]
Never mind. While I think that updating those GitHub Actions is probably also a good idea (for a separate PR), I think the last run simply choked on trying to install the last of the executor plugins (kueue) with one error and all of the storage plugins with another error. See [the CI logs](https://github.com/snakemake/snakemake-plugin-catalog/actions/runs/9803263953/job/27069166278#step:5:20).

For `kueue` this is:
```
Running Sphinx v7.2.6
[...]
Collecting snakemake-executor-plugin-kueue
Error installing snakemake-executor-plugin-kueue or retrieving metadata: Not a valid plugin: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/micromamba/envs/14ca1438e96d464694d3d372e35dfdf9/lib/python3.12/site-packages/snakemake_interface_common/plugin_registry/__init__.py", line 31, in __init__
    self.collect_plugins()
  File "/home/runner/micromamba/envs/14ca1438e96d464694d3d372e35dfdf9/lib/python3.12/site-packages/snakemake_interface_common/plugin_registry/__init__.py", line 77, in collect_plugins
    module = importlib.import_module(moduleinfo.name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/14ca1438e96d464694d3d372e35dfdf9/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/runner/micromamba/envs/14ca1438e96d464694d3d372e35dfdf9/lib/python3.12/site-packages/snakemake_executor_plugin_kueue/__init__.py", line 7, in <module>
    from .executor import KueueExecutor as Executor  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/14ca1438e96d464694d3d372e35dfdf9/lib/python3.12/site-packages/snakemake_executor_plugin_kueue/executor.py", line 22, in <module>
    import snakemake_executor_plugin_kueue.custom_resource as cr
  File "/home/runner/micromamba/envs/14ca1438e96d464694d3d372e35dfdf9/lib/python3.12/site-packages/snakemake_executor_plugin_kueue/custom_resource.py", line 8, in <module>
    config.load_kube_config()
  File "/home/runner/micromamba/envs/14ca1438e96d464694d3d372e35dfdf9/lib/python3.12/site-packages/kubernetes/config/kube_config.py", line 815, in load_kube_config
    loader = _get_kube_config_loader(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/14ca1438e96d464694d3d372e35dfdf9/lib/python3.12/site-packages/kubernetes/config/kube_config.py", line 772, in _get_kube_config_loader
    raise ConfigException(
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No configuration found.
```

And then all of the storage plugins consistently error with this error pattern (so there's probably some underlying bug in the interface for them):
```
Collecting snakemake-storage-plugin-azure
Error installing snakemake-storage-plugin-azure or retrieving metadata: Not a valid plugin: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/runner/micromamba/envs/cf4dad0311c34807ada094750d5a86bd/lib/python3.12/site-packages/snakemake_interface_storage_plugins/registry/__init__.py", line 17, in <module>
    from snakemake_interface_storage_plugins.registry.plugin import Plugin
  File "/home/runner/micromamba/envs/cf4dad0311c34807ada094750d5a86bd/lib/python3.12/site-packages/snakemake_interface_storage_plugins/registry/plugin.py", line 15, in <module>
    from snakemake_interface_storage_plugins.storage_object import (
  File "/home/runner/micromamba/envs/cf4dad0311c34807ada094750d5a86bd/lib/python3.12/site-packages/snakemake_interface_storage_plugins/storage_object.py", line 24, in <module>
    retry_decorator = retry(tries=3, delay=3, backoff=2, logger=get_logger())
                                                                ^^^^^^^^^^^^
  File "/home/runner/micromamba/envs/cf4dad0311c34807ada094750d5a86bd/lib/python3.12/site-packages/snakemake_interface_common/logging.py", line 9, in get_logger
    from snakemake.logging import logger
  File "/home/runner/micromamba/envs/cf4dad0311c34807ada094750d5a86bd/lib/python3.12/site-packages/snakemake/__init__.py", line 12, in <module>
    from snakemake.shell import shell
  File "/home/runner/micromamba/envs/cf4dad0311c34807ada094750d5a86bd/lib/python3.12/site-packages/snakemake/shell.py", line 17, in <module>
    from snakemake.utils import format, argvquote, cmd_exe_quote
  File "/home/runner/micromamba/envs/cf4dad0311c34807ada094750d5a86bd/lib/python3.12/site-packages/snakemake/utils.py", line 19, in <module>
    from snakemake.io import Namedlist, Wildcards
  File "/home/runner/micromamba/envs/cf4dad0311c34807ada094750d5a86bd/lib/python3.12/site-packages/snakemake/io.py", line 35, in <module>
    from snakemake_interface_storage_plugins.storage_object import StorageObjectTouch
ImportError: cannot import name 'StorageObjectTouch' from partially initialized module 'snakemake_interface_storage_plugins.storage_object' (most likely due to a circular import) (/home/runner/micromamba/envs/cf4dad0311c34807ada094750d5a86bd/lib/python3.12/site-packages/snakemake_interface_storage_plugins/storage_object.py)
```

**Comment by cmeesters** [comment]
> While I think that updating those GitHub Actions is probably also a good idea 

ah, I think, this applies to a number of (sub)repos. Will work on it on my part. Have a nice weekend you two!

**Comment by johanneskoester** [comment]
Fixed, catalog is online again.
